name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

env:
  IMAGE_NAME: fakestore-gateway
  IMAGE_TAG: ${{ github.sha }}

jobs:

  commit:
    name: Commit - Build & Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test:unit

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Save Docker image as tarball
        run: docker save -o image.tar $IMAGE_NAME:$IMAGE_TAG

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
            name: app-image
            path: image.tar

  acceptance:
    name: Acceptance - Run Acceptance Tests
    needs: commit
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2


      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
         name: app-image

      - name: Load Docker image
        run: docker load -i image.tar

      - name: Run container in background
        run: |
          docker run -d --name test-container -p 3000:3000 ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Wait for container to be ready
        run: |
          for i in {1..10}; do
            curl -s http://localhost:3000/api-docs && break || sleep 3
          done

      - name: Install dependencies for acceptance tests
        run: npm install

      - name: Run acceptance tests
        run: npm run test:acceptance

      - name: Run K6 performance tests in Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/k6 \
            -w /k6 \
            grafana/k6 run tests/performance/performance_test.js \
            --summary-export=artifacts/summary.json


        # Uploads summary.json as artifact
      - name: Upload performance summary
        uses: actions/upload-artifact@v4
        with:
          name: performance-summary
          path: artifacts/summary.json


      - name: Stop and remove test container
        if: always()
        run: |
          docker stop test-container
          docker rm test-container

      - name: Login to Docker Hub
        run: |
          echo "Login to Docker Hub"

      - name: Build and push Docker image
        run: |
          echo "Publish successfull image To Registry"


  release:
    name: Release - Deploy to Production
    needs: acceptance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        run: |
          echo "Login to Docker Hub"

      - name: Build and push Docker image
        run: |
          echo "Pull image from Registry"

      - name: Deploy to production
        run: |
          echo "Deploy to PROD"
